import React, { useMemo, useState } from 'react';
import { Alert, Button, Card, Checkbox, Col, DatePicker, Divider, Form, Input, Modal, Progress, Row, Select, Space, Steps, Table, Tag, Typography, Upload, message } from 'antd';
import { CheckCircleOutlined, CloudUploadOutlined, DeleteOutlined, DownloadOutlined, FileAddOutlined, PlusOutlined, SaveOutlined, SendOutlined } from '@ant-design/icons';
import dayjs from 'dayjs';
import PortalLayout from '@/Layouts/PortalLayout';

const initialProject = { name: '', description: '', budget: '', project_source: 'System Development', project_nature: 'Planned', project_activity: 'New Implementation (Major)', team_type: 'Internal', team_names: '' };
const initialDocuments = [{ key: 'concept', name: 'Approved Concept Note', phase: 'Initiation', required: true, status: 'Pending' }, { key: 'authority', name: 'e-Government Authority Letter', phase: 'Initiation', required: true, status: 'Pending' }, { key: 'feasibility', name: 'Project Feasibility', phase: 'Initiation', required: false, status: 'Optional' }];
const planningDocuments = ['Project Proposal', 'Project Charter', 'BRD', 'SRS', 'SDD', 'Risk Management Plan', 'Change Management Plan', 'QA Management Plan', 'Procurement Management Plan'];
const executionDocuments = ['FAT Report', 'UAT Report', 'Stakeholder Form', 'Installation Plan'];
const closureDocuments = ['System Implementation Form', 'User Manual', 'Data Migration Report', 'Integration Report', 'Training Report', 'Final Report', 'Post Go-Live Tracker', 'Updated SRS Document', 'Updated SDD Document'];
const statusColor = { Approved: 'green', Pending: 'gold', 'Pending review': 'orange', Completed: 'green', Ongoing: 'blue', 'Not Started': 'default' };
const uploadAccept = { PDF: '.pdf', Excel: '.xls,.xlsx,.csv', DOCX: '.doc,.docx', Other: '' };

function FileTypeUpload() {
    const [fileType, setFileType] = useState('PDF');
    const [fileList, setFileList] = useState([]);
    const beforeUpload = (file) => {
        const accepted = uploadAccept[fileType];
        if (accepted && !accepted.split(',').some((extension) => file.name.toLowerCase().endsWith(extension))) {
            message.error(`${fileType} uploads must use: ${accepted}`);
            return Upload.LIST_IGNORE;
        }
        setFileList([file]);
        message.success(`${file.name} is ready to upload as ${fileType}`);
        return false;
    };
    return <Space wrap><Select value={fileType} onChange={(value) => { setFileType(value); setFileList([]); }} options={Object.keys(uploadAccept).map((value) => ({ value, label: value === 'Other' ? 'Other format' : value }))} style={{ width: 140 }} /><Upload accept={uploadAccept[fileType] || undefined} beforeUpload={beforeUpload} fileList={fileList} onRemove={() => setFileList([])} maxCount={1}><Button icon={<CloudUploadOutlined />}>Choose file</Button></Upload></Space>;
}

function DocumentList({ title, names, documents, onToggle }) {
    return <Card title={title} extra={<FileTypeUpload />}><Space direction="vertical" className="w-full" size="middle">{names.map((name) => { const document = documents.find((item) => item.name === name); const approved = document?.status === 'Approved'; return <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 pb-3" key={name}><Space><FileAddOutlined className="text-red-700" /><span>{name}</span></Space><Space><Tag color={approved ? 'green' : 'gold'}>{document?.status || 'Pending upload'}</Tag><Checkbox checked={approved} onChange={() => onToggle(name)}>{approved ? 'Reviewed' : 'Mark approved'}</Checkbox></Space></div>; })}</Space></Card>;
}

function Initiation({ project, setProject, documents, setDocuments, onComplete }) {
    const [form] = Form.useForm();
    const requiredReady = documents.filter((item) => item.required).every((item) => item.status === 'Approved');
    const save = (values) => { setProject(values); message.success('Project registration saved'); };
    const toggle = (key) => setDocuments(documents.map((item) => item.key === key ? { ...item, status: item.status === 'Approved' ? 'Pending' : 'Approved' } : item));
    return <><Card title="1. Project registration" extra={<Tag color="red">Initiation</Tag>}><Alert className="mb-5" type="info" showIcon message="Capture the project details, then complete and approve the required initiation documents." /><Form form={form} layout="vertical" initialValues={project} onFinish={save}><Row gutter={16}><Col xs={24} lg={12}><Form.Item name="name" label="Project name" rules={[{ required: true }]}><Input placeholder="Enter project name" /></Form.Item></Col><Col xs={24} lg={6}><Form.Item name="budget" label="Budget / cost"><Input prefix="TZS" type="number" /></Form.Item></Col><Col xs={24} lg={6}><Form.Item name="project_nature" label="Project nature"><Select options={[{ value: 'Planned', label: 'Planned' }, { value: 'Adhoc', label: 'Adhoc' }]} /></Form.Item></Col><Col xs={24} lg={12}><Form.Item name="project_source" label="Project source"><Select options={[{ value: 'System Development', label: 'System Development' }, { value: 'Infrastructure Development', label: 'Infrastructure Development' }]} /></Form.Item></Col><Col xs={24} lg={12}><Form.Item name="project_activity" label="Project activity"><Select options={['New Implementation (Major)', 'New Implementation (Minor)', 'Change Request', 'Additional Requirements', 'Review/Enhancement', 'Integration'].map((value) => ({ value, label: value }))} /></Form.Item></Col><Col xs={24}><Form.Item name="description" label="Description"><Input.TextArea rows={3} /></Form.Item></Col><Col xs={24} lg={12}><Form.Item name="team_type" label="Implementation team"><Select options={[{ value: 'Internal', label: 'Internal' }, { value: 'External', label: 'External' }]} /></Form.Item></Col><Col xs={24} lg={12}><Form.Item name="team_names" label="Team member names"><Input placeholder="Enter names separated by commas" /></Form.Item></Col></Row><Button type="primary" htmlType="submit" icon={<SaveOutlined />}>Save registration</Button></Form></Card><Card title="Initiation documents" className="mt-4"><Space direction="vertical" className="w-full" size="middle">{documents.map((document) => <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 pb-3" key={document.key}><span>{document.name}{document.required && <span className="ml-1 text-red-600">*</span>}</span><Space><Tag color={document.status === 'Approved' ? 'green' : document.required ? 'gold' : 'default'}>{document.status}</Tag><Checkbox checked={document.status === 'Approved'} onChange={() => toggle(document.key)}>Approved</Checkbox></Space></div>)}</Space><Divider /><Button type="primary" disabled={!requiredReady || !project.name} onClick={onComplete} icon={<SendOutlined />}>Complete initiation and continue</Button></Card></>;
}

function Planning({ documents, setDocuments, activities, setActivities, onComplete }) {
    const [activity, setActivity] = useState({ activity_name: '', expected_deliverable: '', planned_start_date: null, planned_end_date: null, responsible_person: '' });
    const ready = planningDocuments.every((name) => documents.some((item) => item.name === name && item.status === 'Approved')) && activities.length > 0;
    const addActivity = () => { if (!activity.activity_name || !activity.planned_start_date || !activity.planned_end_date) return message.error('Activity name and planned dates are required'); setActivities([...activities, { ...activity, key: Date.now(), status: 'Not Started' }]); setActivity({ activity_name: '', expected_deliverable: '', planned_start_date: null, planned_end_date: null, responsible_person: '' }); };
    const toggleDocument = (name) => setDocuments(documents.some((item) => item.name === name) ? documents.map((item) => item.name === name ? { ...item, status: item.status === 'Approved' ? 'Pending' : 'Approved' } : item) : [...documents, { name, status: 'Approved' }]);
    const columns = [{ title: 'Activity', dataIndex: 'activity_name' }, { title: 'Deliverable', dataIndex: 'expected_deliverable' }, { title: 'Planned start', dataIndex: 'planned_start_date', render: (value) => value?.format?.('DD MMM YYYY') || value }, { title: 'Planned end', dataIndex: 'planned_end_date', render: (value) => value?.format?.('DD MMM YYYY') || value }, { title: 'Responsible', dataIndex: 'responsible_person' }, { title: '', render: (_, record) => <Button danger type="text" icon={<DeleteOutlined />} onClick={() => setActivities(activities.filter((item) => item.key !== record.key))} /> }];
    return <><Card title="2. Implementation plan" extra={<Tag color="gold">Planning</Tag>}><Row gutter={12} align="bottom"><Col xs={24} lg={5}><Typography.Text>Activity name</Typography.Text><Input value={activity.activity_name} onChange={(event) => setActivity({ ...activity, activity_name: event.target.value })} /></Col><Col xs={24} lg={5}><Typography.Text>Expected deliverable</Typography.Text><Input value={activity.expected_deliverable} onChange={(event) => setActivity({ ...activity, expected_deliverable: event.target.value })} /></Col><Col xs={24} lg={4}><Typography.Text>Start date</Typography.Text><DatePicker className="w-full" value={activity.planned_start_date} onChange={(value) => setActivity({ ...activity, planned_start_date: value })} /></Col><Col xs={24} lg={4}><Typography.Text>End date</Typography.Text><DatePicker className="w-full" value={activity.planned_end_date} onChange={(value) => setActivity({ ...activity, planned_end_date: value })} /></Col><Col xs={24} lg={4}><Button type="primary" icon={<PlusOutlined />} onClick={addActivity}>Add activity</Button></Col></Row><Table className="mt-5" dataSource={activities} columns={columns} pagination={false} scroll={{ x: 800 }} /></Card><div className="mt-4"><DocumentList title="Required planning documents" names={planningDocuments} documents={documents} onToggle={toggleDocument} /></div><Card className="mt-4"><Alert type={ready ? 'success' : 'warning'} showIcon message={ready ? 'Planning is ready for supervisor review.' : 'Add activities and approve every required planning document before continuing.'} /><Button className="mt-4" type="primary" disabled={!ready} onClick={onComplete} icon={<SendOutlined />}>Supervisor approval and continue to execution</Button></Card></>;
}

function Execution({ documents, setDocuments, requirements, setRequirements, activities, onComplete }) {
    const [requirement, setRequirement] = useState({ name: '', planned_start_date: null, planned_end_date: null, actual_start_date: null, actual_end_date: null, remarks: '', score: null });
    const allComplete = requirements.length > 0
        && requirements.every((item) => item.status?.toLowerCase() === 'completed' && (item.score || item.test_score))
        && activities.length > 0
        && activities.every((item) => item.status?.toLowerCase() === 'completed')
        && executionDocuments.every((name) => documents.some((item) => item.name === name && item.status?.toLowerCase() === 'approved'));
    const addRequirement = () => { if (!requirement.name) return message.error('Requirement name is required'); setRequirements([...requirements, { ...requirement, key: Date.now(), status: 'Pending' }]); setRequirement({ name: '', planned_start_date: null, planned_end_date: null, actual_start_date: null, actual_end_date: null, remarks: '', score: null }); };
    const updateRequirement = (key, changes) => setRequirements(requirements.map((item) => { if (item.key !== key) return item; const next = { ...item, ...changes }; return { ...next, status: next.actual_end_date ? 'Completed' : next.actual_start_date ? 'Ongoing' : 'Pending' }; }));
    const columns = [{ title: 'Requirement', dataIndex: 'name' }, { title: 'Actual start', render: (_, item) => <DatePicker value={item.actual_start_date} onChange={(value) => updateRequirement(item.key, { actual_start_date: value })} /> }, { title: 'Actual end', render: (_, item) => <DatePicker value={item.actual_end_date} onChange={(value) => updateRequirement(item.key, { actual_end_date: value })} /> }, { title: 'Status', dataIndex: 'status', render: (value) => <Tag color={statusColor[value]}>{value}</Tag> }, { title: 'UAT score', render: (_, item) => <Select allowClear value={item.score} placeholder="Score" style={{ width: 110 }} onChange={(value) => updateRequirement(item.key, { score: value })} options={[{ value: 'Pass', label: 'Pass' }, { value: 'Fail', label: 'Fail' }]} /> }, { title: 'Remarks', render: (_, item) => <Input value={item.remarks} onChange={(event) => updateRequirement(item.key, { remarks: event.target.value })} /> }];
    const toggleDocument = (name) => setDocuments(documents.some((item) => item.name === name) ? documents.map((item) => item.name === name ? { ...item, status: item.status === 'Approved' ? 'Pending' : 'Approved' } : item) : [...documents, { name, status: 'Approved' }]);
    return <><Card title="3. Execution: requirements traceability" extra={<Tag color="blue">Execution</Tag>}><Alert type="info" showIcon message="Record actual dates and remarks. Status is calculated automatically: Pending, Ongoing, or Completed." /><Row gutter={12} className="mt-5" align="bottom"><Col xs={24} lg={8}><Typography.Text>Requirement from SRS</Typography.Text><Input value={requirement.name} onChange={(event) => setRequirement({ ...requirement, name: event.target.value })} /></Col><Col xs={24} lg={5}><Typography.Text>Planned start</Typography.Text><DatePicker className="w-full" value={requirement.planned_start_date} onChange={(value) => setRequirement({ ...requirement, planned_start_date: value })} /></Col><Col xs={24} lg={5}><Typography.Text>Planned end</Typography.Text><DatePicker className="w-full" value={requirement.planned_end_date} onChange={(value) => setRequirement({ ...requirement, planned_end_date: value })} /></Col><Col xs={24} lg={4}><Button type="primary" icon={<PlusOutlined />} onClick={addRequirement}>Add requirement</Button></Col></Row><Table className="mt-5" dataSource={requirements} columns={columns} pagination={false} scroll={{ x: 1000 }} /></Card><div className="mt-4"><DocumentList title="Required execution documents" names={executionDocuments} documents={documents} onToggle={toggleDocument} /></div><Card className="mt-4"><Alert type={allComplete ? 'success' : 'warning'} showIcon message={allComplete ? 'Execution is complete and ready for closure review.' : 'Complete activities, requirements, UAT scores, and execution documents before closure.'} /><Button className="mt-4" type="primary" disabled={!allComplete} onClick={onComplete} icon={<SendOutlined />}>Continue to closure</Button></Card></>;
}

function Closure({ documents, setDocuments, onClose }) {
    const [lessons, setLessons] = useState('');
    const ready = closureDocuments.every((name) => documents.some((item) => item.name === name && item.status === 'Approved'));
    const toggleDocument = (name) => setDocuments(documents.some((item) => item.name === name) ? documents.map((item) => item.name === name ? { ...item, status: item.status === 'Approved' ? 'Pending' : 'Approved' } : item) : [...documents, { name, status: 'Approved' }]);
    return <><DocumentList title="4. Closure documents" names={closureDocuments} documents={documents} onToggle={toggleDocument} /><Card className="mt-4" title="Lessons learned and final review"><Form layout="vertical"><Form.Item label="Lessons learned"><Input.TextArea rows={5} value={lessons} onChange={(event) => setLessons(event.target.value)} placeholder="Capture lessons, recommendations, and improvements" /></Form.Item><Space><Button icon={<DownloadOutlined />}>Generate closure report</Button><Button type="primary" disabled={!ready} onClick={onClose} icon={<CheckCircleOutlined />}>Close project</Button></Space></Form></Card></>;
}

export default function Workflow({ project: persistedProject }) {
    const phaseIndex = { Initiation: 0, Planning: 1, Execution: 2, Closure: 3 };
    const [phase, setPhase] = useState(phaseIndex[persistedProject?.phase] ?? 0);
    const [project, setProject] = useState(() => ({ ...initialProject, ...persistedProject }));
    const [documents, setDocuments] = useState(() => persistedProject?.documents?.map((document) => ({ ...document, key: document.id, name: document.document_type, status: document.status })) || []);
    const [activities, setActivities] = useState(() => persistedProject?.activities || []);
    const [requirements, setRequirements] = useState(() => (persistedProject?.requirements || []).map((item) => ({
        ...item,
        key: item.key || item.id,
        name: item.name || item.requirement_description,
        score: item.score || item.test_score,
        status: item.status || 'Pending',
    })));
    const [closed, setClosed] = useState(false);
    const stepItems = ['Initiation', 'Planning', 'Execution', 'Closure'].map((title, index) => ({ title, status: index < phase ? 'finish' : index === phase ? 'process' : 'wait' }));
    const progress = Math.round((phase / 3) * 100);
    const content = useMemo(() => { if (closed) return <Card><Alert type="success" showIcon message="Project closed successfully" description="All required workflow stages, documents, requirements, testing, and attestations have been completed." /></Card>; if (phase === 0) return <Initiation project={project} setProject={setProject} documents={documents} setDocuments={setDocuments} onComplete={() => setPhase(1)} />; if (phase === 1) return <Planning documents={documents} setDocuments={setDocuments} activities={activities} setActivities={setActivities} onComplete={() => setPhase(2)} />; if (phase === 2) return <Execution documents={documents} setDocuments={setDocuments} requirements={requirements} setRequirements={setRequirements} activities={activities} onComplete={() => setPhase(3)} />; return <Closure documents={documents} setDocuments={setDocuments} onClose={() => setClosed(true)} />; }, [phase, project, documents, activities, requirements, closed]);
    return <PortalLayout activeKey="initiation"><div className="page-heading"><div><Typography.Text className="eyebrow">PROJECT LIFECYCLE</Typography.Text><Typography.Title level={1}>{project.name || 'Project'}</Typography.Title><Typography.Paragraph type="secondary">Project #{project.id}: follow the process from registration through closure.</Typography.Paragraph></div><Tag color={closed ? 'green' : 'red'}>{closed ? 'CLOSED' : `PHASE ${phase + 1} OF 4`}</Tag></div><Card className="mb-4"><Steps current={phase} items={stepItems} responsive /><Progress percent={closed ? 100 : progress} strokeColor="#9e292f" /></Card>{content}</PortalLayout>;
}
