import React from 'react';
import { Button, Card, Checkbox, Form, Input, Typography, message } from 'antd';
import { LockOutlined, MailOutlined } from '@ant-design/icons';
import { Link, useForm } from '@inertiajs/react';

export default function Login({ errors = {} }) {
    const { data, setData, post, processing } = useForm({ email: '', password: '', remember: false });
    const submit = () => post('/login', { onError: () => message.error('Please check your sign-in details.') });
    return <main className="auth-page"><section className="auth-hero"><div className="auth-logo">NS</div><Typography.Text className="auth-kicker">NSSF PROJECT MANAGEMENT SYSTEM</Typography.Text><Typography.Title>One portal for every project.</Typography.Title><Typography.Paragraph>Coordinate projects, approvals, documents, and delivery milestones from initiation to closure.</Typography.Paragraph><div className="auth-stat"><strong>04</strong><span>controlled project phases</span></div></section><section className="auth-panel"><Card bordered={false}><Typography.Title level={2}>Sign in</Typography.Title><Typography.Paragraph type="secondary">Access your project operations workspace.</Typography.Paragraph><Form layout="vertical" onFinish={submit}><Form.Item label="Email address" validateStatus={errors.email ? 'error' : ''} help={errors.email}><Input prefix={<MailOutlined />} value={data.email} onChange={(event) => setData('email', event.target.value)} placeholder="name@organization.go.tz" /></Form.Item><Form.Item label="Password" validateStatus={errors.password ? 'error' : ''} help={errors.password}><Input.Password prefix={<LockOutlined />} value={data.password} onChange={(event) => setData('password', event.target.value)} placeholder="Enter your password" /></Form.Item><div className="auth-options"><Checkbox checked={data.remember} onChange={(event) => setData('remember', event.target.checked)}>Remember me</Checkbox><a href="mailto:support@nssf.go.tz">Forgot password?</a></div><Button block type="primary" htmlType="submit" loading={processing}>Sign in</Button></Form><div className="auth-switch">Don't have an account? <Link href="/register">Create an account</Link></div><Link className="back-home" href="/">Back to portal home</Link></Card></section></main>;
}
