import React from 'react';
import { Button, Card, Checkbox, Form, Input, Typography, message } from 'antd';
import { LockOutlined, MailOutlined } from '@ant-design/icons';
import { useForm } from '@inertiajs/react';

export default function Login({ errors = {} }) {
    const { data, setData, post, processing } = useForm({ email: '', password: '', remember: false });
    const submit = () => post('/login', { onError: () => message.error('Please check your sign-in details.') });
    return <main className="auth-page"><section className="auth-hero"><img className="auth-logo" src="/images/nssf%20logo.png" alt="NSSF logo" /><Typography.Text className="auth-kicker">ICT MANAGEMENT SYSTEM (ICTMS)</Typography.Text><Typography.Title>Project Management</Typography.Title><Typography.Paragraph>Manage project plans, approvals, requirements, and delivery progress in one secure workspace.</Typography.Paragraph><div className="auth-stat"><strong>Secure access</strong><span>Accounts are created and assigned roles by the system administrator.</span></div></section><section className="auth-panel"><Card bordered={false}><img className="auth-panel-logo" src="/images/nssf%20logo.png" alt="NSSF logo" /><Typography.Title level={2}>Sign in</Typography.Title><Typography.Paragraph type="secondary">Enter your credentials to continue to ICTMS.</Typography.Paragraph><Form layout="vertical" onFinish={submit}><Form.Item label="Email address" validateStatus={errors.email ? 'error' : ''} help={errors.email}><Input prefix={<MailOutlined />} value={data.email} onChange={(event) => setData('email', event.target.value)} placeholder="name@organization.go.tz" /></Form.Item><Form.Item label="Password" validateStatus={errors.password ? 'error' : ''} help={errors.password}><Input.Password prefix={<LockOutlined />} value={data.password} onChange={(event) => setData('password', event.target.value)} placeholder="Enter your password" /></Form.Item><div className="auth-options"><Checkbox checked={data.remember} onChange={(event) => setData('remember', event.target.checked)}>Remember me</Checkbox><a href="mailto:support@nssf.go.tz">Need help?</a></div><Button block type="primary" htmlType="submit" loading={processing}>Sign in</Button></Form><p className="account-notice">New accounts and access roles are issued by the system administrator.</p></Card></section></main>;
}
