import React from 'react';
import { Button, Card, Form, Input, Select, Typography, message } from 'antd';
import { IdcardOutlined, LockOutlined, MailOutlined, UserOutlined } from '@ant-design/icons';
import { Link, useForm } from '@inertiajs/react';

const roles = [
    { value: 'analyst', label: 'System Analyst', description: 'Manage activities, requirements, testing, and project updates.' },
    { value: 'supervisor', label: 'Analyst Supervisor', description: 'Review submissions, documents, plans, and project progression.' },
    { value: 'manager', label: 'Manager (SDMM / IDMM)', description: 'Attest to project information and delivery evidence.' },
    { value: 'dict', label: 'DICT Reviewer', description: 'Provide final DICT attestation and oversight.' },
];

export default function Register({ errors = {} }) {
    const { data, setData, post, processing } = useForm({ name: '', email: '', role: 'analyst', password: '', password_confirmation: '' });
    const submit = () => post('/register', { onError: () => message.error('Please correct the highlighted fields.') });
    return <main className="auth-page auth-register"><section className="auth-hero"><div className="auth-logo">NS</div><Typography.Text className="auth-kicker">NSSF PROJECT MANAGEMENT SYSTEM</Typography.Text><Typography.Title>Start your project workspace.</Typography.Title><Typography.Paragraph>Choose the role that matches your responsibilities. Your access will follow the project process and approval rules.</Typography.Paragraph><div className="role-rail"><span>01</span><span>Register</span><span>02</span><span>Work</span><span>03</span><span>Close</span></div></section><section className="auth-panel"><Card bordered={false}><Typography.Title level={2}>Create account</Typography.Title><Typography.Paragraph type="secondary">Tell us who you are in the project lifecycle.</Typography.Paragraph><Form layout="vertical" onFinish={submit}><Form.Item label="Full name" validateStatus={errors.name ? 'error' : ''} help={errors.name}><Input prefix={<UserOutlined />} value={data.name} onChange={(event) => setData('name', event.target.value)} placeholder="Enter your full name" /></Form.Item><Form.Item label="Email address" validateStatus={errors.email ? 'error' : ''} help={errors.email}><Input prefix={<MailOutlined />} value={data.email} onChange={(event) => setData('email', event.target.value)} placeholder="name@organization.go.tz" /></Form.Item><Form.Item label="Register as" validateStatus={errors.role ? 'error' : ''} help={errors.role}><Select value={data.role} onChange={(value) => setData('role', value)} options={roles.map((role) => ({ value: role.value, label: <span><strong>{role.label}</strong><small className="role-description">{role.description}</small></span> }))} optionLabelProp="label" /></Form.Item><Form.Item label="Password" validateStatus={errors.password ? 'error' : ''} help={errors.password}><Input.Password prefix={<LockOutlined />} value={data.password} onChange={(event) => setData('password', event.target.value)} placeholder="Minimum 8 characters" /></Form.Item><Form.Item label="Confirm password"><Input.Password prefix={<LockOutlined />} value={data.password_confirmation} onChange={(event) => setData('password_confirmation', event.target.value)} placeholder="Repeat your password" /></Form.Item><Button block type="primary" htmlType="submit" loading={processing} icon={<IdcardOutlined />}>Create account</Button></Form><div className="auth-switch">Already registered? <Link href="/login">Sign in</Link></div><Link className="back-home" href="/">Back to portal home</Link></Card></section></main>;
}
